Update alias to match rename
Looks like #1 broke this:
```
$ brew install cockroachdb/go/go
==> Tapping cockroachdb/go
Cloning into '/usr/local/Homebrew/Library/Taps/cockroachdb/homebrew-go'...
...
Error: Broken alias: /usr/local/Homebrew/Library/Taps/cockroachdb/homebrew-go/Aliases/go@1.8.rb
Error: Cannot tap cockroachdb/go: invalid syntax in tap!
```